version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
